/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classprojectoop;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author arets
 */
public class GrupPageForm extends javax.swing.JFrame {
    DatabaseTableCreater dbc = new DatabaseTableCreater();
    private Integer profileId;
   
    // Auto-generated code...

    // Refresh the group combo box with the updated list of groups
   private void refreshGroupComboBox() {
    allGrups.removeAllItems();
    List<String> existingGroups = dbc.getExistingGroups();
    
    for (String groupName : existingGroups) {
        allGrups.addItem(groupName);
    }
    System.out.println("Existing Groups: " + existingGroups);
}
    
    /**
     * Creates new form frontPage
     */
    public GrupPageForm() {
        initComponents();
       // Set the location relative to the center of the screen
        setLocationRelativeTo(null); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        addUserToGroup = new javax.swing.JButton();
        createGroupBtn = new javax.swing.JButton();
        newAccountBtn = new javax.swing.JButton();
        userTF = new javax.swing.JTextField();
        userNameLbl = new javax.swing.JLabel();
        userEmailLbl = new javax.swing.JLabel();
        groupNameLbl = new javax.swing.JLabel();
        groupNameTF = new javax.swing.JTextField();
        descriptionTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        newAccountLbl = new javax.swing.JLabel();
        allGrups = new javax.swing.JComboBox<>();
        passroedLbl = new javax.swing.JLabel();
        returnBtn = new javax.swing.JButton();
        topTextLbl = new javax.swing.JLabel();
        mainPageImageLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 500));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLayeredPane1.setMinimumSize(new java.awt.Dimension(720, 500));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addUserToGroup.setBackground(new java.awt.Color(0, 0, 0));
        addUserToGroup.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        addUserToGroup.setForeground(new java.awt.Color(255, 255, 255));
        addUserToGroup.setText("Add user To Group");
        addUserToGroup.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        addUserToGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserToGroupActionPerformed(evt);
            }
        });
        jLayeredPane1.add(addUserToGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 260, 50));

        createGroupBtn.setBackground(new java.awt.Color(255, 153, 0));
        createGroupBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createGroupBtn.setText("Create Group");
        createGroupBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        createGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGroupBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(createGroupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 130, 40));

        newAccountBtn.setBackground(new java.awt.Color(255, 153, 0));
        newAccountBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        newAccountBtn.setText("New Account");
        newAccountBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        newAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAccountBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(newAccountBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 130, 40));

        userTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        userTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTFActionPerformed(evt);
            }
        });
        jLayeredPane1.add(userTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 400, 40));

        userNameLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        userNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        userNameLbl.setText("User Name ");
        jLayeredPane1.add(userNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 120, 40));

        userEmailLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        userEmailLbl.setForeground(new java.awt.Color(255, 255, 255));
        userEmailLbl.setText("Description");
        jLayeredPane1.add(userEmailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 120, 40));

        groupNameLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        groupNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        groupNameLbl.setText("Group Name ");
        jLayeredPane1.add(groupNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 130, 40));

        groupNameTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        groupNameTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        jLayeredPane1.add(groupNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 400, 40));

        descriptionTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        descriptionTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        descriptionTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionTFActionPerformed(evt);
            }
        });
        jLayeredPane1.add(descriptionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 400, 40));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Exit");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 100, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("All Groups");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 110, 40));

        newAccountLbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        newAccountLbl.setForeground(new java.awt.Color(255, 255, 255));
        newAccountLbl.setText("for new Users ");
        jLayeredPane1.add(newAccountLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 100, 40));

        allGrups.setEditable(true);
        allGrups.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        allGrups.setForeground(new java.awt.Color(255, 255, 255));
        allGrups.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grups" }));
        allGrups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allGrupsActionPerformed(evt);
            }
        });
        jLayeredPane1.add(allGrups, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 130, 40));

        passroedLbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        passroedLbl.setForeground(new java.awt.Color(255, 255, 255));
        passroedLbl.setText("create the Group");
        jLayeredPane1.add(passroedLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 110, 40));

        returnBtn.setBackground(new java.awt.Color(255, 153, 51));
        returnBtn.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        returnBtn.setText("Return");
        returnBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(returnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 110, 40));

        topTextLbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        topTextLbl.setForeground(new java.awt.Color(255, 255, 255));
        topTextLbl.setText("Create your Group Page ");
        jLayeredPane1.add(topTextLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 440, 50));

        mainPageImageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/Background_page_Front_Page.png"))); // NOI18N
        mainPageImageLbl.setAlignmentY(0.0F);
        mainPageImageLbl.setPreferredSize(new java.awt.Dimension(720, 500));
        jLayeredPane1.add(mainPageImageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, -1));
        mainPageImageLbl.getAccessibleContext().setAccessibleDescription("");

        jPanel1.add(jLayeredPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 500));
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    
    // Event handler for the "New Account" button
    private void newAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccountBtnActionPerformed
// TODO add your handling code here:
UserProfileForm upf = new UserProfileForm();
        upf.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_newAccountBtnActionPerformed

    
    // Event handler for the "Add User to Group" button
    private void addUserToGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserToGroupActionPerformed
        // TODO add your handling code here:
      String user = userTF.getText();
    String email = descriptionTF.getText();
    String selectedGroup = (String) allGrups.getSelectedItem();

    // Check if the user and group exist
    if (!dbc.userExists(user)) {
        System.out.println("User does not exist.");
        JOptionPane.showMessageDialog(null, "User does not exist.");
        return;
    }
    if (!dbc.groupExists(selectedGroup)) {
        System.out.println("Group does not exist.");
        JOptionPane.showMessageDialog(null, "Group does not exist.");
        return;
    }
    // Add user to the 'UserGroupMembers' table
    dbc.addUserToGroup(user, selectedGroup);
    System.out.println("User added to the group successfully.");

    }//GEN-LAST:event_addUserToGroupActionPerformed

    
    private void userTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTFActionPerformed

    private void descriptionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_jButton1ActionPerformed

     // Event handler for the "Create Group" button
    private void createGroupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGroupBtnActionPerformed
        // TODO add your handling code here:
             // Check if the user exists in the "users" table
             String userName = userTF.getText();
             if (!dbc.isUserExists(userName)) {
             System.out.println("User does not exist. Cannot create a group.");
             JOptionPane.showMessageDialog(null, "User does not exist. Cannot create a group.");
             return;
            }

            String groupName = groupNameTF.getText(); // User Name 
            String description = descriptionTF.getText(); // The description of the Group 
            String createdBy = userTF.getText(); // Assuming createdBy is the user name for simplicity

            // Call the createGroup method
            dbc.createGroup(groupName, description, createdBy);
            
            // Refresh the JComboBox with the updated list of groups
            refreshGroupComboBox();
        

    }//GEN-LAST:event_createGroupBtnActionPerformed
    
    // Event handler for the group combo box
    private void allGrupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allGrupsActionPerformed
        // TODO add your handling code here:
        // Add this code to create and populate the JComboBox
         JComboBox<Object> allGrups = new JComboBox<>();
         List<String> existingGroups = dbc.getExistingGroups();
         for (String groupName : existingGroups) {
         allGrups.addItem(groupName);

        }
        // the selection change directly in the existing ActionListener
      Object selectedGroup = allGrups.getSelectedItem();
    if (selectedGroup != null) {
        // Handle the selected group
        System.out.println("Selected Group: " + selectedGroup.toString());
        // perform additional actions based on the selected group
    }
    }//GEN-LAST:event_allGrupsActionPerformed
     

    // Event handler for the "Return" button
    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
         FrameForPanelsOpen ffpo = null;
         ffpo = new FrameForPanelsOpen();
        ffpo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnBtnActionPerformed
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrupPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrupPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrupPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrupPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrupPageForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserToGroup;
    private javax.swing.JComboBox<String> allGrups;
    private javax.swing.JButton createGroupBtn;
    private javax.swing.JTextField descriptionTF;
    private javax.swing.JLabel groupNameLbl;
    private javax.swing.JTextField groupNameTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mainPageImageLbl;
    private javax.swing.JButton newAccountBtn;
    private javax.swing.JLabel newAccountLbl;
    private javax.swing.JLabel passroedLbl;
    private javax.swing.JButton returnBtn;
    private javax.swing.JLabel topTextLbl;
    private javax.swing.JLabel userEmailLbl;
    private javax.swing.JLabel userNameLbl;
    private javax.swing.JTextField userTF;
    // End of variables declaration//GEN-END:variables

    public void setSelected(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private static class groupComboBox {

        private static void removeAllItems() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private static void addItem(String groupName) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public groupComboBox() {
        }
    }
}
