/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package classprojectoop;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * Andrei Re.
 * @author Samantha/Andrei Retsja 
 */
public class MessagesFrame extends javax.swing.JInternalFrame {
      DatabaseTableCreater dbc = new DatabaseTableCreater ();
    
    
       private void displayNewsFeeds() {
    
        // Display news feeds in a TextArea = newsFeedTA
    try {
        List<String> newsFeeds = dbc.getNewsFeeds();

        // TextArea named newsFeedTextArea to display the NewsFeeds
        newsFeedTA.setText(""); // Clear existing content

        // newsFeedPost
        for (String newsFeed : newsFeeds) {
        newsFeedTA.append(newsFeed + "\n");
        JOptionPane.showMessageDialog(null, "");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    
    /**
     * Creates new form MessagesFrame
     */
    public MessagesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        newsFeedTA = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 255, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 550, 160));

        newsFeedTA.setColumns(20);
        newsFeedTA.setRows(5);
        jScrollPane2.setViewportView(newsFeedTA);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 590, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/Background_page_Front_Page2333x2073.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea newsFeedTA;
    // End of variables declaration//GEN-END:variables
}
