/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package classprojectoop;
import java.awt.Container;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.SQLException;

import java.util.List;

import javax.swing.JFileChooser;

import javax.swing.JOptionPane;


/**
 *
 * @author Samantha/Andrei Retsja
 */
public class NewsFeedFrame extends javax.swing.JInternalFrame {
     DatabaseTableCreater dbc;
    UserImagesDAO userImagesDAO;
    // Variables declaration - do not modify
    private String username;
    
    
    
    /**
     * Creates new form NewsFeedFrame
     */
    public NewsFeedFrame() throws SQLException {
   dbc = new DatabaseTableCreater();
        userImagesDAO = new UserImagesDAO((Connection) dbc.getConnection());
        initComponents();
    }
    
     /**
     * Display the existing news feeds.
     */
    
     private void displayNewsFeeds() {
        try {
            List<String> newsFeeds = dbc.getNewsFeeds();
            newsFeedTA.setText(""); // Clear existing content

            for (String newsFeed : newsFeeds) {
                newsFeedTA.append(newsFeed + "\n");
                JOptionPane.showMessageDialog(null, "");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

      /**
     * Post a new news feed.
     */
     
    private void postNewsFeed() {
        String newsFeed = newsTF.getText();
        String userName = userNameTF.getText();
        dbc.createNewsFeed(userName, newsFeed);
        displayNewsFeeds();
    }

   
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        addNewsLbl = new javax.swing.JLabel();
        newsFeedPanel = new javax.swing.JPanel();
        newsFeedLbl = new javax.swing.JLabel();
        linksPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        newsFeedTA = new javax.swing.JTextArea();
        imageLabel = new javax.swing.JLabel();
        newsTF = new javax.swing.JTextField();
        postBtn = new javax.swing.JButton();
        userNameTF = new javax.swing.JTextField();
        userNameLbl = new javax.swing.JLabel();
        addPhoto = new javax.swing.JButton();
        pressButtonLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 102, 0));

        backgroundPanel.setBackground(new java.awt.Color(255, 102, 0));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addNewsLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addNewsLbl.setForeground(new java.awt.Color(255, 255, 255));
        addNewsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addNewsLbl.setText("Add News ");
        backgroundPanel.add(addNewsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, 30));

        newsFeedPanel.setBackground(new java.awt.Color(102, 102, 255));

        newsFeedLbl.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        newsFeedLbl.setText("News Feed");

        javax.swing.GroupLayout newsFeedPanelLayout = new javax.swing.GroupLayout(newsFeedPanel);
        newsFeedPanel.setLayout(newsFeedPanelLayout);
        newsFeedPanelLayout.setHorizontalGroup(
            newsFeedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newsFeedPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(newsFeedLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addGap(419, 419, 419))
        );
        newsFeedPanelLayout.setVerticalGroup(
            newsFeedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newsFeedPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(newsFeedLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        backgroundPanel.add(newsFeedPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, -1, -1));

        linksPanel.setBackground(new java.awt.Color(255, 255, 255));

        newsFeedTA.setColumns(20);
        newsFeedTA.setRows(5);
        jScrollPane1.setViewportView(newsFeedTA);

        javax.swing.GroupLayout linksPanelLayout = new javax.swing.GroupLayout(linksPanel);
        linksPanel.setLayout(linksPanelLayout);
        linksPanelLayout.setHorizontalGroup(
            linksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linksPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );
        linksPanelLayout.setVerticalGroup(
            linksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linksPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(linksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(linksPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        backgroundPanel.add(linksPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 270, -1, 240));

        newsTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsTFActionPerformed(evt);
            }
        });
        backgroundPanel.add(newsTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 640, 30));

        postBtn.setBackground(new java.awt.Color(51, 102, 255));
        postBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        postBtn.setForeground(new java.awt.Color(255, 255, 255));
        postBtn.setText("Post");
        postBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        postBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postBtnActionPerformed(evt);
            }
        });
        backgroundPanel.add(postBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 100, 40));
        backgroundPanel.add(userNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 130, 30));

        userNameLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        userNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        userNameLbl.setText("User Name");
        backgroundPanel.add(userNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 100, 30));

        addPhoto.setBackground(new java.awt.Color(255, 102, 0));
        addPhoto.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        addPhoto.setText("Add Photo");
        addPhoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        addPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPhotoActionPerformed(evt);
            }
        });
        backgroundPanel.add(addPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 110, 40));

        pressButtonLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pressButtonLbl.setForeground(new java.awt.Color(255, 255, 255));
        pressButtonLbl.setText("Press button to add your Photo");
        backgroundPanel.add(pressButtonLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 280, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void newsTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newsTFActionPerformed

    /**
     * Handles the action when the post button is clicked.
     * @param evt The action event.
     */
    
    private void postBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postBtnActionPerformed
          // TODO add your handling code here:
    String newsFeed = newsTF.getText();  //  news feed text field
    String userName = userNameTF.getText();  // username
    dbc.createNewsFeed(userName, newsFeed);

    // After posting, refresh the displayed news feeds
    displayNewsFeeds();

    }//GEN-LAST:event_postBtnActionPerformed

      /**
     * Handles the action when the add photo button is clicked.
     * @param evt The action event.
     */
    
    private void addPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPhotoActionPerformed
        // TODO add your handling code here:
       JFileChooser fileChooser = new JFileChooser();
       int result = fileChooser.showOpenDialog(this);

       if (result == JFileChooser.APPROVE_OPTION) {
       File selectedFile = fileChooser.getSelectedFile();

      // Check if the selectedFile is not null
       if (selectedFile != null && selectedFile.exists()) {
       try {
         // Convert the image file to bytes
        byte[] imageData = Files.readAllBytes(selectedFile.toPath());

        // Insert the image into the userimages table
        userImagesDAO.insertImage(imageData, username);

        System.out.println("Image saved to database.");
    } catch (IOException e) {
        e.printStackTrace();
        // Handle the exception appropriately (log it, show a message, etc.)
    }
    } else {
    System.out.println("Invalid or non-existent file selected.");
   }
}

    }//GEN-LAST:event_addPhotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addNewsLbl;
    private javax.swing.JButton addPhoto;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel linksPanel;
    private javax.swing.JLabel newsFeedLbl;
    private javax.swing.JPanel newsFeedPanel;
    private javax.swing.JTextArea newsFeedTA;
    private javax.swing.JTextField newsTF;
    private javax.swing.JButton postBtn;
    private javax.swing.JLabel pressButtonLbl;
    private javax.swing.JLabel userNameLbl;
    private javax.swing.JTextField userNameTF;
    // End of variables declaration//GEN-END:variables

    private void updateJTextAreaComponents(Container contentPane, String newsFeed) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void uploadImage(String username, File selectedFile) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

   
}
