/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classprojectoop;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 * Andrei Re.
 * User profile form class.
 * Allows users to create a new profile.
 * 
 * @author arets
 */
public class UserProfileForm extends javax.swing.JFrame {
    // Instance of DatabaseTableCreater for database operations
    DatabaseTableCreater dbc = new DatabaseTableCreater();
    
   
    // User profile ID
    private Integer profileId;
  
    
    /**
     * Creates new form userProfileForm
     */
    public UserProfileForm() {
        initComponents();
        // Set the location relative to the center of the screen
        setLocationRelativeTo(null); 
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        emailTF = new javax.swing.JTextField();
        userTF = new javax.swing.JTextField();
        exitBtn = new javax.swing.JButton();
        mainPageBtn = new javax.swing.JButton();
        mainPageText1 = new javax.swing.JLabel();
        CreateNewUserBtn = new javax.swing.JButton();
        returnBtn = new javax.swing.JButton();
        userNameLbl = new java.awt.Label();
        label4 = new java.awt.Label();
        passwordLbl = new java.awt.Label();
        passwordTF = new javax.swing.JTextField();
        ageConfirm = new java.awt.Label();
        ageConfirmCB = new javax.swing.JCheckBox();
        mainPageText = new javax.swing.JLabel();
        mainPageRightImage = new javax.swing.JLabel();
        mainPageLeftImage = new javax.swing.JLabel();
        MainPageBackgroundImage = new javax.swing.JLabel();
        mainPageText2 = new javax.swing.JLabel();

        jPanel2.setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(730, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(730, 520));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        jPanel1.add(emailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 278, 370, 41));

        userTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        userTF.setToolTipText("");
        userTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        userTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTFActionPerformed(evt);
            }
        });
        jPanel1.add(userTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 130, 370, 41));

        exitBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 449, 80, 40));

        mainPageBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mainPageBtn.setText("Group Page");
        mainPageBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        mainPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPageBtnActionPerformed(evt);
            }
        });
        jPanel1.add(mainPageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 449, 110, 40));
        mainPageBtn.getAccessibleContext().setAccessibleDescription("");

        mainPageText1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        mainPageText1.setForeground(new java.awt.Color(102, 0, 102));
        mainPageText1.setText("Please Add your Details");
        jPanel1.add(mainPageText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 503, 40));

        CreateNewUserBtn.setBackground(new java.awt.Color(0, 102, 255));
        CreateNewUserBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CreateNewUserBtn.setForeground(new java.awt.Color(255, 255, 255));
        CreateNewUserBtn.setText("Create");
        CreateNewUserBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        CreateNewUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewUserBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CreateNewUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 439, 120, 40));

        returnBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        returnBtn.setText("Return");
        returnBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });
        jPanel1.add(returnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 449, 90, 40));

        userNameLbl.setAlignment(java.awt.Label.CENTER);
        userNameLbl.setBackground(new java.awt.Color(255, 255, 255));
        userNameLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        userNameLbl.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        userNameLbl.setName(""); // NOI18N
        userNameLbl.setText("First Name");
        jPanel1.add(userNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 143, 40));

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setBackground(new java.awt.Color(255, 255, 255));
        label4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        label4.setText("Email");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 278, 140, 40));

        passwordLbl.setAlignment(java.awt.Label.CENTER);
        passwordLbl.setBackground(new java.awt.Color(255, 255, 255));
        passwordLbl.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        passwordLbl.setText("Password");
        jPanel1.add(passwordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 140, 40));

        passwordTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passwordTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        jPanel1.add(passwordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 207, 370, 41));

        ageConfirm.setAlignment(java.awt.Label.CENTER);
        ageConfirm.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        ageConfirm.setText(" I confirm +18");
        jPanel1.add(ageConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 359, 140, 40));

        ageConfirmCB.setBackground(new java.awt.Color(51, 102, 255));
        ageConfirmCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageConfirmCBActionPerformed(evt);
            }
        });
        jPanel1.add(ageConfirmCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 359, 40, 40));

        mainPageText.setBackground(new java.awt.Color(255, 255, 255));
        mainPageText.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        mainPageText.setForeground(new java.awt.Color(255, 255, 255));
        mainPageText.setText("Account User Profile Form");
        mainPageText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 3, true));
        jPanel1.add(mainPageText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 510, 50));

        mainPageRightImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/User_profile_Front_Back_1.png"))); // NOI18N
        mainPageRightImage.setToolTipText("");
        jPanel1.add(mainPageRightImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        mainPageLeftImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/User_profile_Front_Back_1.png"))); // NOI18N
        jPanel1.add(mainPageLeftImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 330, -1));

        MainPageBackgroundImage.setForeground(new java.awt.Color(255, 153, 0));
        MainPageBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/Form_BackGround.png3.png"))); // NOI18N
        jPanel1.add(MainPageBackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 500));
        MainPageBackgroundImage.getAccessibleContext().setAccessibleDescription("");

        mainPageText2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        mainPageText2.setForeground(new java.awt.Color(102, 0, 102));
        mainPageText2.setText("Account User Profile Form");
        jPanel1.add(mainPageText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 500, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Navigates to the Group Page form.
    private void mainPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPageBtnActionPerformed
    // TODO add your handling code here:
          GrupPageForm gpf = new GrupPageForm ();
          gpf.setVisible(true);
          this.setVisible(false);
        
    }//GEN-LAST:event_mainPageBtnActionPerformed

     /**
     * Event handler for the "Create" button.
     * Creates a new user profile based on the provided details.
     */
    
    private void CreateNewUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewUserBtnActionPerformed
        // TODO add your handling code here:
       if (ageConfirmCB.isSelected()) {
        // If selected, the user is confirming they are 18 or older
       JOptionPane.showMessageDialog(null, "Profile Created");
       System.out.println("Age confirmed: 18 or older");
        // Extract user input
       String user = userTF.getText();
       String password = passwordTF.getText();
       String email = emailTF.getText();
       
        // Insert user into the database
       dbc.insertUser(user,password,email,profileId);
       
       // Navigate to the main page
       FrontMainPage fmp = new FrontMainPage();
       fmp.setVisible(true);
        this.setVisible(false);
        }else{
        // If checkBox is not selected,it means at user is not confirming at his are 18 it not let create Form
        // Display a message and prevent the creation of the profile
        JOptionPane.showMessageDialog(null, "Please confirm that you are 18 or older before creating an account.");
        System.out.println("Please confirm that you are 18 or older before creating an account.");
   
    }
        
    }//GEN-LAST:event_CreateNewUserBtnActionPerformed
        //Exits the application.
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
         // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_exitBtnActionPerformed

    //Navigates back to the main panel.
    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
        FrameForPanelsOpen ffpo = new FrameForPanelsOpen();
        ffpo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnBtnActionPerformed
    //
    private void userTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTFActionPerformed
    //Check if the checkbox is selected.
    private void ageConfirmCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageConfirmCBActionPerformed
      // Check if the checkbox is selected
    }//GEN-LAST:event_ageConfirmCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserProfileForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateNewUserBtn;
    private javax.swing.JLabel MainPageBackgroundImage;
    private java.awt.Label ageConfirm;
    private javax.swing.JCheckBox ageConfirmCB;
    private javax.swing.JTextField emailTF;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label4;
    private javax.swing.JButton mainPageBtn;
    private javax.swing.JLabel mainPageLeftImage;
    private javax.swing.JLabel mainPageRightImage;
    private javax.swing.JLabel mainPageText;
    private javax.swing.JLabel mainPageText1;
    private javax.swing.JLabel mainPageText2;
    private java.awt.Label passwordLbl;
    private javax.swing.JTextField passwordTF;
    private javax.swing.JButton returnBtn;
    private java.awt.Label userNameLbl;
    private javax.swing.JTextField userTF;
    // End of variables declaration//GEN-END:variables

    private void insertUser(String user, String password, String email) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    void setSelected(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
